### ISSUE TITLE
Blank app icon in Flipper Catalog

### ISSUE THREAD

**Issue by hedger** [xtruan/flipper-chess#2]
Current icons in Flipper App Catalog is blank - since the source icon is required to be purely black-and-white (1-bit color depth). However, current icon uses #0A0A0A as dark color.

p.s. if you choose to fix that, please don't forget to increase app version in application.fam when submitting an update to catalog

**Comment by xtruan** [comment]
@hedger Fixed, no idea how that happened. Also, just FYI this app catalog is a super cool idea, thanks for putting it together! 😃
