### ISSUE TITLE
Illegal move onto same position allowed, causing "suicide"

### ISSUE THREAD

**Issue by piotrwicijowski** [xtruan/flipper-chess#3]
Affected version: 1.9.0
Reproduction steps:
1. Set  both players as human
2. Start new game
3. Move any white piece (does not matter which and where)
4. Move black piece out of its default position
5. During whites turn double click on the black piece moved in step 4
6. Result - black piece is removed, even though no action should happen

**Comment by xtruan** [comment]
I have reproduced this, very strange. I will look into it when I get a chance.
